name: CI
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - "main"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use nix devshell
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: .#devShells.x86_64-linux.ci
      - name: CI
        run: flake-ci
